import { BusinessSegmentConfig } from '../types';

export const padariaSegment: BusinessSegmentConfig = {
  id: 'padaria',
  name: 'Padaria & Confeitaria',
  emoji: '🥖',
  tagline: 'Gestão de Padarias, Panifícios e Fornadas',
  description: 'Controle de pães por kg/unidade, fornadas matinais/vespertinas, lanches de balcão e insumos de panificação.',
  primaryColor: '#d97706', // Âmbar dourado
  secondaryColor: '#b45309',
  defaultCategories: [
    'Pães & Fornadas',
    'Frios & Laticínios',
    'Confeitaria & Bolos',
    'Cafés & Bebidas Quentes',
    'Salgados & Lanches',
    'Sucos & Gelados',
    'Mercearia Matinal',
  ],
  defaultUnits: ['kg', 'g', 'un', 'L', 'pct', 'cx'],
  terminology: {
    productSingular: 'Item de Padaria',
    productPlural: 'Itens & Fornadas',
    newProductLabel: 'Novo Item / Pão',
    inventoryLabel: 'Estoque de Farinhas & Insumos',
    recipeLabel: 'Ficha da Receita / Batelada',
    salesLabel: 'Vendas de Balcão & Caixa',
    customerLabel: 'Clientes da Padaria',
    categoryLabel: 'Setores da Padaria',
  },
  features: {
    hasSizes: true,
    hasCrustsOrBorders: false,
    hasFlavors: false,
    hasAddons: true,
    hasCombos: true,
    hasRecipeCostCMV: true,
    hasInventory: true,
    hasDelivery: false,
    hasCodeSKU: true,
    hasPreparationTime: true,
  },
  suggestedProducts: [
    {
      name: 'Pão Francês Tradicional (Crocante)',
      category: 'Pães & Fornadas',
      price: 18.9, // Preço por kg ou unidade
      cost: 6.2,
      unit: 'kg',
      description: 'Fornadas quentes a cada 40 minutos. Casca crocante e miolo leve.',
    },
    {
      name: 'Pão de Queijo Mineiro da Casa',
      category: 'Salgados & Lanches',
      price: 4.5,
      cost: 1.4,
      unit: 'un',
      description: 'Feito com legítimo queijo curado e polvilho artesanal.',
    },
    {
      name: 'Bolo Caseiro de Cenoura com Chocolate',
      category: 'Confeitaria & Bolos',
      price: 32.0,
      cost: 11.5,
      unit: 'un',
      description: 'Fatia ou bolo inteiro coberto com brigadeiro cremoso belga.',
    },
    {
      name: 'Café Pingado com Leite Vaporizado',
      category: 'Cafés & Bebidas Quentes',
      price: 6.5,
      cost: 1.8,
      unit: 'un',
      description: 'Café expresso moído na hora com leite integral cremoso no copo americano.',
    },
  ],
  suggestedInventory: [
    { name: 'Farinha de Trigo Panificação 25kg', category: 'Farinhas & Grãos', unit: 'kg', currentQuantity: 125, minQuantity: 50, cost: 3.9 },
    { name: 'Fermento Biológico Fresco', category: 'Fermentos & Químicos', unit: 'kg', currentQuantity: 10, minQuantity: 3, cost: 18.0 },
    { name: 'Margarina / Manteiga Folhada', category: 'Gorduras', unit: 'kg', currentQuantity: 20, minQuantity: 5, cost: 22.5 },
    { name: 'Polvilho Doce Especial', category: 'Farinhas & Grãos', unit: 'kg', currentQuantity: 30, minQuantity: 10, cost: 8.5 },
    { name: 'Queijo Meia Cura Ralado', category: 'Laticínios', unit: 'kg', currentQuantity: 15, minQuantity: 4, cost: 39.0 },
    { name: 'Sacos de Papel Kraft Pão (Fardo)', category: 'Embalagens', unit: 'cx', currentQuantity: 8, minQuantity: 2, cost: 45.0 },
  ],
};
