import { BusinessSegmentConfig } from '../types';

export const pizzariaSegment: BusinessSegmentConfig = {
  id: 'pizzaria',
  name: 'Pizzaria',
  emoji: '🍕',
  tagline: 'Gestão Completa de Pizzarias & Fornarias',
  description: 'Controle de massas, bordas recheadas, sabores meio a meio, fichas técnicas e entregas.',
  primaryColor: '#ef4444', // Vermelho artesanal
  secondaryColor: '#f97316',
  defaultCategories: [
    'Pizzas Tradicionais',
    'Pizzas Especiais',
    'Pizzas Doces',
    'Bordas & Adicionais',
    'Calzones',
    'Bebidas & Refrigerantes',
    'Sobremesas',
  ],
  defaultUnits: ['kg', 'g', 'un', 'L', 'pct', 'cx'],
  terminology: {
    productSingular: 'Pizza / Item',
    productPlural: 'Pizzas & Itens',
    newProductLabel: 'Nova Pizza / Item',
    inventoryLabel: 'Estoque de Insumos',
    recipeLabel: 'Ficha Técnica da Pizza',
    salesLabel: 'Vendas & Entregas',
    customerLabel: 'Clientes',
    categoryLabel: 'Categorias de Pizzas',
  },
  features: {
    hasSizes: true,
    hasCrustsOrBorders: true,
    hasFlavors: true,
    hasAddons: true,
    hasCombos: true,
    hasRecipeCostCMV: true,
    hasInventory: true,
    hasDelivery: true,
    hasCodeSKU: false,
    hasPreparationTime: true,
  },
  suggestedProducts: [
    {
      name: 'Pizza Calabresa Especial',
      category: 'Pizzas Tradicionais',
      price: 52.0,
      cost: 16.5,
      hasSizes: true,
      sizes: [
        { id: 's-broto', name: 'Broto (4 fatias)', slices: 4, maxFlavors: 1, price: 34.0, cost: 11.0 },
        { id: 's-media', name: 'Média (6 fatias)', slices: 6, maxFlavors: 2, price: 44.0, cost: 14.0 },
        { id: 's-grande', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 3, price: 52.0, cost: 16.5 },
        { id: 's-familia', name: 'Gigante (12 fatias)', slices: 12, maxFlavors: 4, price: 64.0, cost: 20.0 },
      ],
      description: 'Molho pelati artesanal, mussarela de cura média, calabresa defumada fatiada fininha e cebola roxa fresca.',
    },
    {
      name: 'Pizza Mussarela Clássica',
      category: 'Pizzas Tradicionais',
      price: 48.0,
      cost: 15.0,
      hasSizes: true,
      sizes: [
        { id: 's-broto', name: 'Broto (4 fatias)', slices: 4, maxFlavors: 1, price: 30.0, cost: 10.0 },
        { id: 's-grande', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 2, price: 48.0, cost: 15.0 },
      ],
      description: 'Massa fermentada 48h, molho de tomate rústico, generosa camada de queijo mussarela e orégano chileno.',
    },
    {
      name: 'Pizza Frango com Catupiry Original',
      category: 'Pizzas Especiais',
      price: 58.0,
      cost: 19.5,
      hasSizes: true,
      sizes: [
        { id: 's-grande', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 2, price: 58.0, cost: 19.5 },
      ],
      description: 'Peito de frango desfiado temperado com ervas finas e legítimo requeijão cremoso Catupiry.',
    },
    {
      name: 'Refrigerante Guaraná Antarctica 2L',
      category: 'Bebidas & Refrigerantes',
      price: 13.0,
      cost: 7.2,
      description: 'Garrafa pet 2 litros gelada.',
    },
  ],
  suggestedInventory: [
    { name: 'Farinha de Trigo Especial 00', category: 'Massas & Farinhas', unit: 'kg', currentQuantity: 50, minQuantity: 15, cost: 4.8 },
    { name: 'Queijo Mussarela Peça', category: 'Laticínios', unit: 'kg', currentQuantity: 28, minQuantity: 10, cost: 32.5 },
    { name: 'Linguiça Calabresa Fatiada', category: 'Frios & Carnes', unit: 'kg', currentQuantity: 18, minQuantity: 6, cost: 24.0 },
    { name: 'Requeijão Catupiry Bisnaga', category: 'Laticínios', unit: 'kg', currentQuantity: 12, minQuantity: 4, cost: 38.0 },
    { name: 'Caixa de Pizza Oitavada 35cm', category: 'Embalagens', unit: 'un', currentQuantity: 150, minQuantity: 40, cost: 2.3 },
  ],
};
