import {
  AddOn,
  Category,
  Combo,
  Customer,
  InventoryItem,
  Order,
  Product,
  ProductCrust,
  ProductSize,
  Settings,
  Transaction,
} from '../../types';

export const INITIAL_SETTINGS: Settings = {
  id: 'settings',
  name: 'Meu Negócio',
  category: 'Lanchonete / Restaurante',
  slogan: 'O melhor sabor da cidade',
  phone: '(11) 98765-4321',
  whatsapp: '11987654321',
  email: 'contato@meunegocio.com.br',
  address: 'Rua Principal, 100',
  city: 'São Paulo',
  state: 'SP',
  theme: 'dark',
  primaryColor: '#ef4444',
  secondaryColor: '#fca5a5',
  currency: 'R$',
  defaultDeliveryFee: 7.0,
  isDemoMode: false,
  setupCompleted: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-pizzas',
    name: 'Pizzas',
    icon: '🍕',
    color: '#ef4444',
    subcategories: ['Tradicionais', 'Especiais', 'Doces', 'Premium'],
    order: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-bebidas',
    name: 'Bebidas',
    icon: '🥤',
    color: '#3b82f6',
    subcategories: ['Refrigerantes 2L', 'Latas & Sucos', 'Cervejas', 'Águas'],
    order: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-sobremesas',
    name: 'Sobremesas',
    icon: '🍰',
    color: '#ec4899',
    subcategories: ['Pizzas Doces', 'Doces & Mousses', 'Gelados'],
    order: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-acompanhamentos',
    name: 'Acompanhamentos',
    icon: '🍟',
    color: '#f59e0b',
    subcategories: ['Porções', 'Pães de Alho', 'Molhos Especiais'],
    order: 4,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-combos',
    name: 'Combos',
    icon: '🎁',
    color: '#10b981',
    subcategories: ['Promoções', 'Família', 'Casal', 'Individual'],
    order: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-outros',
    name: 'Outros',
    icon: '➕',
    color: '#8b5cf6',
    subcategories: ['Diversos'],
    order: 6,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const STANDARD_PIZZA_SIZES: ProductSize[] = [
  { id: 'size-broto', name: 'Broto', slices: 4, maxFlavors: 1, price: 28.0, cost: 9.5 },
  { id: 'size-media', name: 'Média', slices: 6, maxFlavors: 2, price: 42.9, cost: 13.5 },
  { id: 'size-grande', name: 'Grande (Padrão)', slices: 8, maxFlavors: 2, price: 54.9, cost: 16.5 },
  { id: 'size-familia', name: 'Família / Gigante', slices: 12, maxFlavors: 3, price: 68.9, cost: 21.0 },
];

export const STANDARD_PIZZA_CRUSTS: ProductCrust[] = [
  { id: 'crust-none', name: 'Sem borda recheada', price: 0.0, cost: 0.0, available: true },
  { id: 'crust-catupiry', name: 'Borda Catupiry Original', price: 8.0, cost: 2.8, available: true },
  { id: 'crust-cheddar', name: 'Borda Cheddar Cremoso', price: 8.0, cost: 2.8, available: true },
  { id: 'crust-chocolate', name: 'Borda Chocolate ao Leite', price: 10.0, cost: 3.5, available: true },
  { id: 'crust-vulcao', name: 'Borda Vulcão Quatro Queijos', price: 14.0, cost: 4.8, available: true },
];

export const DEMO_ADDONS: AddOn[] = [
  { id: 'add-1', name: 'Mussarela Extra', price: 8.0, cost: 2.8, category: 'Queijos', available: true, createdAt: new Date().toISOString(), isDemo: true },
  { id: 'add-2', name: 'Bacon Crocante Especial', price: 7.0, cost: 2.5, category: 'Carnes', available: true, createdAt: new Date().toISOString(), isDemo: true },
  { id: 'add-3', name: 'Catupiry Extra', price: 8.0, cost: 2.8, category: 'Queijos', available: true, createdAt: new Date().toISOString(), isDemo: true },
  { id: 'add-4', name: 'Cheddar Cremoso Extra', price: 8.0, cost: 2.8, category: 'Queijos', available: true, createdAt: new Date().toISOString(), isDemo: true },
  { id: 'add-5', name: 'Calabresa Fatiada Extra', price: 6.0, cost: 2.0, category: 'Carnes', available: true, createdAt: new Date().toISOString(), isDemo: true },
  { id: 'add-6', name: 'Azeitonas Pretas sem Caroço', price: 4.0, cost: 1.2, category: 'Temperos', available: true, createdAt: new Date().toISOString(), isDemo: true },
  { id: 'add-7', name: 'Alho Frito Dourado', price: 4.0, cost: 0.8, category: 'Temperos', available: true, createdAt: new Date().toISOString(), isDemo: true },
  { id: 'add-8', name: 'Cebola Roxa Caramelizada', price: 5.0, cost: 1.5, category: 'Vegetais', available: true, createdAt: new Date().toISOString(), isDemo: true },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Pizza Calabresa Especial',
    code: 'PIZ-001',
    categoryId: 'cat-pizzas',
    category: 'Pizzas',
    subCategory: 'Tradicionais',
    description: 'Molho artesanal, calabresa fatiada premium, cebola roxa, azeitonas pretas e orégano.',
    price: 54.9,
    cost: 16.5,
    available: true,
    hasSizes: true,
    sizes: [
      { id: 's-1', name: 'Broto (4 fatias)', slices: 4, maxFlavors: 1, price: 29.9, cost: 9.5 },
      { id: 's-2', name: 'Média (6 fatias)', slices: 6, maxFlavors: 2, price: 44.9, cost: 13.5 },
      { id: 's-3', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 2, price: 54.9, cost: 16.5 },
      { id: 's-4', name: 'Família (12 fatias)', slices: 12, maxFlavors: 3, price: 69.9, cost: 21.0 },
    ],
    crusts: STANDARD_PIZZA_CRUSTS,
    maxFlavors: 2,
    preparationTimeMinutes: 15,
    yieldUnits: 1,
    recipeInstructions: 'Abrir o disco de massa fina (35cm), espalhar 100ml de molho pelati artesanal, cobrir com 250g de mussarela, distribuir 180g de fatias finas de calabresa e cebola roxa. Forno a lenha/elétrico a 300°C por 3 a 5 minutos até dourar a borda. Finalizar com orégano e azeitonas.',
    recipe: [
      {
        id: 'ri-1',
        inventoryItemId: 'inv-3',
        inventoryItemName: 'Farinha de Trigo Especial 00',
        quantity: 250,
        unit: 'g',
        unitCost: 0.0058,
        totalCost: 1.45,
      },
      {
        id: 'ri-2',
        inventoryItemId: 'inv-4',
        inventoryItemName: 'Molho de Tomate Pelati Artesanal',
        quantity: 100,
        unit: 'ml' as any,
        unitCost: 0.0095,
        totalCost: 0.95,
      },
      {
        id: 'ri-3',
        inventoryItemId: 'inv-1',
        inventoryItemName: 'Mussarela Especial',
        quantity: 250,
        unit: 'g',
        unitCost: 0.032,
        totalCost: 8.0,
      },
      {
        id: 'ri-4',
        inventoryItemId: 'inv-2',
        inventoryItemName: 'Linguiça Calabresa Defumada',
        quantity: 180,
        unit: 'g',
        unitCost: 0.026,
        totalCost: 4.68,
      },
      {
        id: 'ri-5',
        inventoryItemId: 'inv-5',
        inventoryItemName: 'Orégano Chileno Desidratado',
        quantity: 5,
        unit: 'g',
        unitCost: 0.045,
        totalCost: 0.23,
      },
      {
        id: 'ri-6',
        inventoryItemId: 'inv-6',
        inventoryItemName: 'Caixas de Pizza Oitavadas 35cm',
        quantity: 1,
        unit: 'un',
        unitCost: 1.2,
        totalCost: 1.2,
      },
    ],
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-2',
    name: 'Pizza Margherita Di Bufala',
    code: 'PIZ-002',
    categoryId: 'cat-pizzas',
    category: 'Pizzas',
    subCategory: 'Especiais',
    description: 'Molho de tomate pelati, mussarela de búfala, rodelas de tomate fresco e manjericão.',
    price: 59.9,
    cost: 18.2,
    available: true,
    hasSizes: true,
    sizes: [
      { id: 's-1', name: 'Broto (4 fatias)', slices: 4, maxFlavors: 1, price: 32.9, cost: 10.5 },
      { id: 's-2', name: 'Média (6 fatias)', slices: 6, maxFlavors: 2, price: 48.9, cost: 14.5 },
      { id: 's-3', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 2, price: 59.9, cost: 18.2 },
      { id: 's-4', name: 'Família (12 fatias)', slices: 12, maxFlavors: 3, price: 74.9, cost: 23.0 },
    ],
    crusts: STANDARD_PIZZA_CRUSTS,
    maxFlavors: 2,
    preparationTimeMinutes: 14,
    yieldUnits: 1,
    recipeInstructions: 'Abrir disco 35cm, espalhar molho pelati, 280g de queijo mussarela, fatias de tomate fresco e queijo parmesão. Assar a 320°C por 4 minutos. Ao sair do forno, dispor as folhas frescas de manjericão e fio de azeite extravirgem.',
    recipe: [
      {
        id: 'ri-7',
        inventoryItemId: 'inv-3',
        inventoryItemName: 'Farinha de Trigo Especial 00',
        quantity: 250,
        unit: 'g',
        unitCost: 0.0058,
        totalCost: 1.45,
      },
      {
        id: 'ri-8',
        inventoryItemId: 'inv-4',
        inventoryItemName: 'Molho de Tomate Pelati Artesanal',
        quantity: 120,
        unit: 'ml' as any,
        unitCost: 0.0095,
        totalCost: 1.14,
      },
      {
        id: 'ri-9',
        inventoryItemId: 'inv-1',
        inventoryItemName: 'Mussarela Especial',
        quantity: 320,
        unit: 'g',
        unitCost: 0.032,
        totalCost: 10.24,
      },
      {
        id: 'ri-10',
        inventoryItemId: 'inv-6',
        inventoryItemName: 'Caixas de Pizza Oitavadas 35cm',
        quantity: 1,
        unit: 'un',
        unitCost: 1.2,
        totalCost: 1.2,
      },
    ],
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-3',
    name: 'Pizza Quatro Queijos Real',
    code: 'PIZ-003',
    categoryId: 'cat-pizzas',
    category: 'Pizzas',
    subCategory: 'Especiais',
    description: 'Mussarela especial, provolone defumado, gorgonzola cremoso e catupiry original.',
    price: 64.9,
    cost: 21.0,
    available: true,
    hasSizes: true,
    sizes: [
      { id: 's-1', name: 'Broto (4 fatias)', slices: 4, maxFlavors: 1, price: 35.9, cost: 11.5 },
      { id: 's-2', name: 'Média (6 fatias)', slices: 6, maxFlavors: 2, price: 52.9, cost: 16.5 },
      { id: 's-3', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 2, price: 64.9, cost: 21.0 },
      { id: 's-4', name: 'Família (12 fatias)', slices: 12, maxFlavors: 3, price: 79.9, cost: 25.5 },
    ],
    crusts: STANDARD_PIZZA_CRUSTS,
    maxFlavors: 2,
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-4',
    name: 'Pizza Frango com Catupiry',
    code: 'PIZ-004',
    categoryId: 'cat-pizzas',
    category: 'Pizzas',
    subCategory: 'Tradicionais',
    description: 'Peito de frango desfiado temperado, milho verde e autêntico requeijão Catupiry.',
    price: 58.0,
    cost: 17.8,
    available: true,
    hasSizes: true,
    sizes: [
      { id: 's-1', name: 'Broto (4 fatias)', slices: 4, maxFlavors: 1, price: 31.9, cost: 10.0 },
      { id: 's-2', name: 'Média (6 fatias)', slices: 6, maxFlavors: 2, price: 46.9, cost: 14.0 },
      { id: 's-3', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 2, price: 58.0, cost: 17.8 },
      { id: 's-4', name: 'Família (12 fatias)', slices: 12, maxFlavors: 3, price: 72.9, cost: 22.5 },
    ],
    crusts: STANDARD_PIZZA_CRUSTS,
    maxFlavors: 2,
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-5',
    name: 'Pizza Portuguesa Tradicional',
    code: 'PIZ-005',
    categoryId: 'cat-pizzas',
    category: 'Pizzas',
    subCategory: 'Tradicionais',
    description: 'Presunto cozido magro, ovos, cebola, ervilhas frescas, mussarela e azeitonas.',
    price: 56.9,
    cost: 18.0,
    available: true,
    hasSizes: true,
    sizes: [
      { id: 's-1', name: 'Broto (4 fatias)', slices: 4, maxFlavors: 1, price: 30.9, cost: 10.0 },
      { id: 's-2', name: 'Média (6 fatias)', slices: 6, maxFlavors: 2, price: 45.9, cost: 14.0 },
      { id: 's-3', name: 'Grande (8 fatias)', slices: 8, maxFlavors: 2, price: 56.9, cost: 18.0 },
      { id: 's-4', name: 'Família (12 fatias)', slices: 12, maxFlavors: 3, price: 71.9, cost: 23.0 },
    ],
    crusts: STANDARD_PIZZA_CRUSTS,
    maxFlavors: 2,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-6',
    name: 'Pizza Doce Nutella com Morango',
    code: 'PIZ-006',
    categoryId: 'cat-sobremesas',
    category: 'Sobremesas',
    subCategory: 'Pizzas Doces',
    description: 'Massa leve e crocante, generosa camada de Nutella e morangos frescos selecionados.',
    price: 49.9,
    cost: 17.5,
    available: true,
    hasSizes: true,
    sizes: [
      { id: 's-1', name: 'Broto Doce (4 fatias)', slices: 4, maxFlavors: 1, price: 34.9, cost: 12.0 },
      { id: 's-2', name: 'Média Doce (6 fatias)', slices: 6, maxFlavors: 1, price: 49.9, cost: 17.5 },
    ],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-7',
    name: 'Coca-Cola Original 2L',
    code: 'BEB-001',
    categoryId: 'cat-bebidas',
    category: 'Bebidas',
    subCategory: 'Refrigerantes 2L',
    description: 'Garrafa PET 2 Litros bem gelada.',
    price: 14.0,
    cost: 8.2,
    available: true,
    hasSizes: false,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-8',
    name: 'Guaraná Antarctica 2L',
    code: 'BEB-002',
    categoryId: 'cat-bebidas',
    category: 'Bebidas',
    subCategory: 'Refrigerantes 2L',
    description: 'Garrafa PET 2 Litros gelada.',
    price: 13.0,
    cost: 7.5,
    available: true,
    hasSizes: false,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-9',
    name: 'Água Mineral sem Gás 500ml',
    code: 'BEB-003',
    categoryId: 'cat-bebidas',
    category: 'Bebidas',
    subCategory: 'Águas',
    description: 'Garrafa 500ml gelada.',
    price: 5.0,
    cost: 1.5,
    available: true,
    hasSizes: false,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'prod-10',
    name: 'Pão de Alho Especial Recheado',
    code: 'ACOMP-001',
    categoryId: 'cat-acompanhamentos',
    category: 'Acompanhamentos',
    subCategory: 'Pães de Alho',
    description: 'Porção com 4 unidades crocantes recheadas com queijo e pasta de alho artesanal.',
    price: 19.9,
    cost: 6.8,
    available: true,
    hasSizes: false,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    isDemo: true,
  },
];

export const DEMO_COMBOS: Combo[] = [
  {
    id: 'combo-1',
    name: 'Combo Família Completo',
    description: '1 Pizza Grande Salgada + 1 Pizza Média Doce + 1 Refrigerante 2L.',
    items: [
      { id: 'ci-1', productName: 'Pizza Grande Salgada (Qualquer Sabor)', sizeName: 'Grande', quantity: 1 },
      { id: 'ci-2', productName: 'Pizza Média Doce', sizeName: 'Média', quantity: 1 },
      { id: 'ci-3', productName: 'Coca-Cola 2L', sizeName: '2L', quantity: 1 },
    ],
    originalPrice: 118.8,
    comboPrice: 99.9,
    discount: 18.9,
    cost: 42.2,
    available: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'combo-2',
    name: 'Combo Casal Perfeito',
    description: '1 Pizza Grande + 1 Refrigerante 2L + Borda Recheada de Catupiry Grátis.',
    items: [
      { id: 'ci-4', productName: 'Pizza Grande Especial', sizeName: 'Grande', quantity: 1 },
      { id: 'ci-5', productName: 'Borda Catupiry Original', quantity: 1 },
      { id: 'ci-6', productName: 'Guaraná Antarctica 2L', sizeName: '2L', quantity: 1 },
    ],
    originalPrice: 76.9,
    comboPrice: 65.9,
    discount: 11.0,
    cost: 26.8,
    available: true,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    isDemo: true,
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Carlos Eduardo Silva',
    phone: '(11) 99123-4567',
    address: 'Rua Augusta, 850, Apto 42',
    neighborhood: 'Consolação',
    city: 'São Paulo',
    notes: 'Interfone 42. Prefere entrega sem tocar campainha tarde da noite.',
    totalOrders: 6,
    totalSpent: 412.5,
    lastOrderDate: new Date().toISOString(),
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'cust-2',
    name: 'Mariana Costa Oliveira',
    phone: '(11) 98234-5678',
    address: 'Alameda Santos, 1200, Bloco B Apto 101',
    neighborhood: 'Jardins',
    city: 'São Paulo',
    notes: 'Cliente VIP. Sempre pede borda de catupiry.',
    totalOrders: 9,
    totalSpent: 680.0,
    lastOrderDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'cust-3',
    name: 'Roberto Mendes',
    phone: '(11) 97345-6789',
    address: 'Rua Bela Cintra, 450',
    neighborhood: 'Cerqueira César',
    city: 'São Paulo',
    notes: 'Casa com portão preto.',
    totalOrders: 3,
    totalSpent: 195.0,
    lastOrderDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'cust-4',
    name: 'Juliana Ferreira',
    phone: '(11) 96456-7890',
    address: 'Rua Frei Caneca, 990, Apto 84',
    neighborhood: 'Consolação',
    city: 'São Paulo',
    notes: '',
    totalOrders: 4,
    totalSpent: 268.0,
    lastOrderDate: new Date(Date.now() - 15 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    isDemo: true,
  },
];

export const DEMO_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Mussarela Especial',
    unit: 'kg',
    currentQuantity: 18.5,
    minQuantity: 10.0,
    cost: 32.0,
    category: 'Queijos & Laticínios',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'inv-2',
    name: 'Linguiça Calabresa Defumada',
    unit: 'kg',
    currentQuantity: 12.0,
    minQuantity: 8.0,
    cost: 26.0,
    category: 'Frios & Carnes',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'inv-3',
    name: 'Farinha de Trigo Especial 00',
    unit: 'kg',
    currentQuantity: 45.0,
    minQuantity: 20.0,
    cost: 5.8,
    category: 'Massas & Farinhas',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'inv-4',
    name: 'Molho de Tomate Pelati Artesanal',
    unit: 'L',
    currentQuantity: 6.5,
    minQuantity: 15.0,
    cost: 9.5,
    category: 'Molhos & Condimentos',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'inv-5',
    name: 'Orégano Chileno Desidratado',
    unit: 'kg',
    currentQuantity: 1.8,
    minQuantity: 1.0,
    cost: 45.0,
    category: 'Temperos',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'inv-6',
    name: 'Caixas de Pizza Oitavadas 35cm',
    unit: 'un',
    currentQuantity: 24,
    minQuantity: 50,
    cost: 2.8,
    category: 'Embalagens',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'inv-7',
    name: 'Refrigerantes Coca-Cola 2L',
    unit: 'un',
    currentQuantity: 32,
    minQuantity: 12,
    cost: 8.2,
    category: 'Bebidas',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'inv-8',
    name: 'Catupiry Original Bisnaga',
    unit: 'kg',
    currentQuantity: 8.0,
    minQuantity: 5.0,
    cost: 42.0,
    category: 'Queijos & Laticínios',
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 101,
    customerName: 'Carlos Eduardo Silva',
    customerPhone: '(11) 99123-4567',
    customerAddress: 'Rua Augusta, 850, Apto 42 - Consolação',
    customerId: 'cust-1',
    type: 'Entrega',
    origin: 'WhatsApp',
    status: 'Novo',
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        name: 'Pizza Calabresa Especial',
        category: 'Pizzas',
        size: { name: 'Grande (8 fatias)', slices: 8, price: 54.9 },
        crust: { name: 'Borda Catupiry Original', price: 8.0 },
        addons: [{ id: 'add-2', name: 'Bacon Crocante Especial', price: 7.0, quantity: 1 }],
        price: 69.9,
        cost: 21.8,
        quantity: 1,
        notes: 'Caprichar na cebola roxa',
        subtotal: 69.9,
      },
      {
        id: 'item-2',
        productId: 'prod-7',
        name: 'Coca-Cola Original 2L',
        category: 'Bebidas',
        price: 14.0,
        cost: 8.2,
        quantity: 1,
        subtotal: 14.0,
      },
    ],
    subtotal: 83.9,
    deliveryFee: 7.0,
    discount: 0,
    total: 90.9,
    paymentMethod: 'Pix',
    paymentStatus: 'Pago',
    notes: 'Cliente pediu para confirmar chave Pix após aceite.',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    isDemo: true,
  },
  {
    id: 'ord-102',
    orderNumber: 102,
    customerName: 'Mariana Costa Oliveira',
    customerPhone: '(11) 98234-5678',
    customerAddress: 'Alameda Santos, 1200, Bloco B Apto 101 - Jardins',
    customerId: 'cust-2',
    type: 'Entrega',
    origin: 'iFood',
    status: 'Em preparo',
    items: [
      {
        id: 'item-3',
        productId: 'prod-3',
        name: 'Pizza Quatro Queijos Real',
        category: 'Pizzas',
        size: { name: 'Grande (8 fatias)', slices: 8, price: 64.9 },
        flavors: ['Quatro Queijos Real', 'Margherita Di Bufala'],
        crust: { name: 'Borda Catupiry Original', price: 8.0 },
        price: 72.9,
        cost: 23.8,
        quantity: 1,
        notes: 'Massa fina e bem assada',
        subtotal: 72.9,
      },
      {
        id: 'item-4',
        productId: 'prod-6',
        name: 'Pizza Doce Nutella com Morango',
        category: 'Sobremesas',
        size: { name: 'Média Doce (6 fatias)', slices: 6, price: 49.9 },
        price: 49.9,
        cost: 17.5,
        quantity: 1,
        subtotal: 49.9,
      },
    ],
    subtotal: 122.8,
    deliveryFee: 8.0,
    discount: 5.0,
    total: 125.8,
    paymentMethod: 'Cartão de Crédito',
    paymentStatus: 'Pago',
    notes: 'Entregar na portaria.',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    isDemo: true,
  },
  {
    id: 'ord-103',
    orderNumber: 103,
    customerName: 'Mesa 4 (Balcão)',
    customerPhone: '(11) 90000-0000',
    type: 'Balcão',
    origin: 'Balcão',
    status: 'Pronto',
    items: [
      {
        id: 'item-5',
        productId: 'prod-2',
        name: 'Pizza Margherita Di Bufala',
        category: 'Pizzas',
        size: { name: 'Grande (8 fatias)', slices: 8, price: 59.9 },
        price: 59.9,
        cost: 18.2,
        quantity: 1,
        subtotal: 59.9,
      },
      {
        id: 'item-6',
        productId: 'prod-8',
        name: 'Guaraná Antarctica 2L',
        category: 'Bebidas',
        price: 13.0,
        cost: 7.5,
        quantity: 1,
        subtotal: 13.0,
      },
    ],
    subtotal: 72.9,
    deliveryFee: 0,
    discount: 0,
    total: 72.9,
    paymentMethod: 'Cartão de Débito',
    paymentStatus: 'Pago',
    notes: 'Consumo local.',
    createdAt: new Date(Date.now() - 50 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    isDemo: true,
  },
  {
    id: 'ord-104',
    orderNumber: 104,
    customerName: 'Juliana Ferreira',
    customerPhone: '(11) 96456-7890',
    customerAddress: 'Rua Frei Caneca, 990, Apto 84 - Consolação',
    customerId: 'cust-4',
    type: 'Entrega',
    origin: 'Instagram',
    status: 'Saiu para entrega',
    items: [
      {
        id: 'item-7',
        productId: 'prod-4',
        name: 'Pizza Frango com Catupiry',
        category: 'Pizzas',
        size: { name: 'Grande (8 fatias)', slices: 8, price: 58.0 },
        price: 58.0,
        cost: 17.8,
        quantity: 1,
        notes: 'Sem orégano',
        subtotal: 58.0,
      },
    ],
    subtotal: 58.0,
    deliveryFee: 7.0,
    discount: 0,
    total: 65.0,
    paymentMethod: 'Dinheiro',
    paymentStatus: 'Pendente',
    changeFor: 100.0,
    notes: 'Levar troco para R$ 100,00.',
    createdAt: new Date(Date.now() - 65 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    isDemo: true,
  },
  {
    id: 'ord-105',
    orderNumber: 105,
    customerName: 'Roberto Mendes',
    customerPhone: '(11) 97345-6789',
    customerAddress: 'Rua Bela Cintra, 450 - Cerqueira César',
    customerId: 'cust-3',
    type: 'Retirada',
    origin: 'Telefone',
    status: 'Concluído',
    items: [
      {
        id: 'item-8',
        productId: 'combo-1',
        name: 'Combo Família Completo',
        category: 'Combos',
        price: 99.9,
        cost: 42.2,
        quantity: 1,
        notes: '1 Calabresa + 1 Nutella + Coca 2L',
        subtotal: 99.9,
      },
    ],
    subtotal: 99.9,
    deliveryFee: 0,
    discount: 0,
    total: 99.9,
    paymentMethod: 'Pix',
    paymentStatus: 'Pago',
    notes: 'Cliente retirou no balcão.',
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    isDemo: true,
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    description: 'Venda Pedido #105 (Combo Família Completo)',
    amount: 99.9,
    category: 'Vendas',
    paymentMethod: 'Pix',
    orderId: 'ord-105',
    date: new Date(Date.now() - 40 * 60000).toISOString(),
    isDemo: true,
  },
  {
    id: 'tx-2',
    type: 'income',
    description: 'Venda Pedido #103 (Mesa 4 Balcão)',
    amount: 72.9,
    category: 'Vendas',
    paymentMethod: 'Cartão de Débito',
    orderId: 'ord-103',
    date: new Date(Date.now() - 50 * 60000).toISOString(),
    isDemo: true,
  },
  {
    id: 'tx-3',
    type: 'expense',
    description: 'Compra de lenha ecológica para forno',
    amount: 180.0,
    category: 'Outros',
    paymentMethod: 'Pix',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    notes: '10 sacos de lenha reflorestada',
    isDemo: true,
  },
  {
    id: 'tx-4',
    type: 'expense',
    description: 'Reposição semanal de Embalagens e Caixas',
    amount: 280.0,
    category: 'Embalagens',
    paymentMethod: 'Pix',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    notes: '100 caixas oitavadas e lacres de segurança',
    isDemo: true,
  },
  {
    id: 'tx-5',
    type: 'expense',
    description: 'Conta de Energia Elétrica',
    amount: 450.0,
    category: 'Energia',
    paymentMethod: 'Pix',
    date: new Date(Date.now() - 7 * 86400000).toISOString(),
    notes: 'Mês de referência anterior',
    isDemo: true,
  },
];
